name: API Gateway CICD

on:
  push:
    branches:
    - dev-api-gateway
  pull_request:
    branches:
    - dev-api-gateway

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Set Up Java
    - name: Set Up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17.0.1'
    - run: | 
        mvn package
        cd target
        java -jar api-gateway-0.0.1-SNAPSHOT.jar
